name: testops_python

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ALLURE_ENDPOINT: https://demo.qatools.cloud/api
  ALLURE_PROJECT_ID: 429
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_RESULTS: allure-results

jobs:
  autotests:
    environment: test_env
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allurectl-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare results dir
        run: mkdir -p $ALLURE_RESULTS

      - name: Run tests with Allure TestOps integration
        run: |
          allurectl watch \
            --endpoint $ALLURE_ENDPOINT \
            --project-id $ALLURE_PROJECT_ID \
            --token $ALLURE_TOKEN \
            -- pytest --alluredir=$ALLURE_RESULTS

      - name: Check allure-results directory
        if: always()
        run: ls -la $ALLURE_RESULTS
